### ISSUE TITLE
source code 

### ISSUE THREAD

**Issue by momentum-coding** [hackmebroo/CCFP#2]
Excellent work. When will the code be made public

**Comment by momentum-coding** [comment]
I'm replicating the results of the article but ran into some difficulities. Can you release some key implementation code first so i can check my own problems. Thank you very much.

**Comment by hackmebroo** [comment]
> I'm replicating the results of the article but ran into some difficulities. Can you release some key implementation code first so i can check my own problems. Thank you very much.

Sorry about that. Please email to me, and I'll send you the key implementation code.

**Comment by momentum-coding** [comment]
Thank you for reply. There is another question about implementation. If LDP module is designed for generating new domains, why is it still used during inference?

**Comment by hackmebroo** [comment]
If we remove the LDP module directly, the model will collapse since there are learnable parameters in the LDP modules, and we find that randomly applying LDP during training can mitigate this situation, but there may be a slight decline in the performance. 

Additionally, as mentioned in the paper, the LDP modules can be used as a test-time augmentation technology, since our approach can also transform possible target domain features to the learnable worst-case domain with the help of LDP modules, and the network is trained to extract semantic information from the features in such a learnable domain.

**Comment by hackmebroo** [comment]
> Thank you for reply. There is another question about implementation. If LDP module is designed for generating new domains, why is it still used during inference?

If we remove the LDP module directly, the model will collapse since there are learnable parameters in the LDP modules, and we find that randomly applying LDP during training can mitigate this situation, but there may be a slight decline in the performance.

Additionally, as mentioned in the paper, the LDP modules can be used as a test-time augmentation technology, since our approach can also transform possible target domain features to the learnable worst-case domain with the help of LDP modules, and the network is trained to extract semantic information from the features in such a learnable domain.

**Comment by momentum-coding** [comment]
Thanks for explaining.But your code show that the LDP is randomly used determined by variable 'training' during training,during testing the LDP is abandoned by setting training to False.

**Comment by momentum-coding** [comment]
Thanks for explaining.But your code shows that the LDP is randomly used determined by variable 'training' during training,during testing the LDP is abandoned by setting training to False.

**Comment by hackmebroo** [comment]
> Thanks for explaining.But your code shows that the LDP is randomly used determined by variable 'training' during training,during testing the LDP is abandoned by setting training to False.

I used this approach to test the impact of randomly applying the LDP modules during training, and you can keep the variable 'training' as true during testing.
